# Generated by Django 4.0.6 on 2025-01-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0002_tarjeta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
